/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated/admin.whatsapp'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminRankingRouteImport } from './routes/_authenticated/admin.ranking'
import { Route as AuthenticatedAdminMensagensRouteImport } from './routes/_authenticated/admin.mensagens'
import { Route as AuthenticatedAdminFerramentasRouteImport } from './routes/_authenticated/admin.ferramentas'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedAdminBotRouteImport } from './routes/_authenticated/admin.bot'
import { Route as AuthenticatedAdminAutomacaoRouteImport } from './routes/_authenticated/admin.automacao'
import { Route as AuthenticatedAdminAparenciaRouteImport } from './routes/_authenticated/admin.aparencia'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/admin/whatsapp',
    path: '/admin/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRankingRoute =
  AuthenticatedAdminRankingRouteImport.update({
    id: '/admin/ranking',
    path: '/admin/ranking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMensagensRoute =
  AuthenticatedAdminMensagensRouteImport.update({
    id: '/admin/mensagens',
    path: '/admin/mensagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFerramentasRoute =
  AuthenticatedAdminFerramentasRouteImport.update({
    id: '/admin/ferramentas',
    path: '/admin/ferramentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/admin/catalogo',
    path: '/admin/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBotRoute = AuthenticatedAdminBotRouteImport.update({
  id: '/admin/bot',
  path: '/admin/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAutomacaoRoute =
  AuthenticatedAdminAutomacaoRouteImport.update({
    id: '/admin/automacao',
    path: '/admin/automacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAparenciaRoute =
  AuthenticatedAdminAparenciaRouteImport.update({
    id: '/admin/aparencia',
    path: '/admin/aparencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/admin/aparencia': typeof AuthenticatedAdminAparenciaRoute
  '/admin/automacao': typeof AuthenticatedAdminAutomacaoRoute
  '/admin/bot': typeof AuthenticatedAdminBotRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/ferramentas': typeof AuthenticatedAdminFerramentasRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/admin/aparencia': typeof AuthenticatedAdminAparenciaRoute
  '/admin/automacao': typeof AuthenticatedAdminAutomacaoRoute
  '/admin/bot': typeof AuthenticatedAdminBotRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/ferramentas': typeof AuthenticatedAdminFerramentasRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/admin/aparencia': typeof AuthenticatedAdminAparenciaRoute
  '/_authenticated/admin/automacao': typeof AuthenticatedAdminAutomacaoRoute
  '/_authenticated/admin/bot': typeof AuthenticatedAdminBotRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/ferramentas': typeof AuthenticatedAdminFerramentasRoute
  '/_authenticated/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/_authenticated/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pedidos'
    | '/admin/aparencia'
    | '/admin/automacao'
    | '/admin/bot'
    | '/admin/catalogo'
    | '/admin/ferramentas'
    | '/admin/mensagens'
    | '/admin/ranking'
    | '/admin/usuarios'
    | '/admin/whatsapp'
    | '/admin/'
    | '/api/public/webhooks/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pedidos'
    | '/admin/aparencia'
    | '/admin/automacao'
    | '/admin/bot'
    | '/admin/catalogo'
    | '/admin/ferramentas'
    | '/admin/mensagens'
    | '/admin/ranking'
    | '/admin/usuarios'
    | '/admin/whatsapp'
    | '/admin'
    | '/api/public/webhooks/evolution'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/pedidos'
    | '/_authenticated/admin/aparencia'
    | '/_authenticated/admin/automacao'
    | '/_authenticated/admin/bot'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/ferramentas'
    | '/_authenticated/admin/mensagens'
    | '/_authenticated/admin/ranking'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/admin/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ranking': {
      id: '/_authenticated/admin/ranking'
      path: '/admin/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AuthenticatedAdminRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mensagens': {
      id: '/_authenticated/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AuthenticatedAdminMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ferramentas': {
      id: '/_authenticated/admin/ferramentas'
      path: '/admin/ferramentas'
      fullPath: '/admin/ferramentas'
      preLoaderRoute: typeof AuthenticatedAdminFerramentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bot': {
      id: '/_authenticated/admin/bot'
      path: '/admin/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AuthenticatedAdminBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/automacao': {
      id: '/_authenticated/admin/automacao'
      path: '/admin/automacao'
      fullPath: '/admin/automacao'
      preLoaderRoute: typeof AuthenticatedAdminAutomacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/aparencia': {
      id: '/_authenticated/admin/aparencia'
      path: '/admin/aparencia'
      fullPath: '/admin/aparencia'
      preLoaderRoute: typeof AuthenticatedAdminAparenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedAdminAparenciaRoute: typeof AuthenticatedAdminAparenciaRoute
  AuthenticatedAdminAutomacaoRoute: typeof AuthenticatedAdminAutomacaoRoute
  AuthenticatedAdminBotRoute: typeof AuthenticatedAdminBotRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminFerramentasRoute: typeof AuthenticatedAdminFerramentasRoute
  AuthenticatedAdminMensagensRoute: typeof AuthenticatedAdminMensagensRoute
  AuthenticatedAdminRankingRoute: typeof AuthenticatedAdminRankingRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedAdminAparenciaRoute: AuthenticatedAdminAparenciaRoute,
  AuthenticatedAdminAutomacaoRoute: AuthenticatedAdminAutomacaoRoute,
  AuthenticatedAdminBotRoute: AuthenticatedAdminBotRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminFerramentasRoute: AuthenticatedAdminFerramentasRoute,
  AuthenticatedAdminMensagensRoute: AuthenticatedAdminMensagensRoute,
  AuthenticatedAdminRankingRoute: AuthenticatedAdminRankingRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
